# yaml-language-server: $schema=../schema/device_profile_v1.json
# Schema version number
version: 1

# The type of configuration schema
kind: DeviceProfile

# Name of the device profile
name: Default

# Profile mappings
mapping: []
