# yaml-language-server: $schema=https://raw.githubusercontent.com/ShadowBlip/InputPlumber/main/rootfs/usr/share/inputplumber/schema/device_profile_v1.json
# Schema version number
version: 1

# The type of configuration schema
kind: DeviceProfile

# Name of the device profile
name: Default

# Target input device(s) to emulate. If unset, the target devices from the device profile will be used.
#target_devices:
#  - gamepad
#  - mouse
#  - keyboard

# Profile mappings
mapping:
  - name: LeftTop
    source_event:
      gamepad:
        button: LeftTop
    target_events:
      - gamepad:
          button: Guide
      - gamepad:
          button: North
  - name: RightTop
    source_event:
      gamepad:
        button: RightTop
    target_events:
      - gamepad:
          button: Guide
      - gamepad:
          button: East
  - name: Keyboard
    source_event:
      gamepad:
        button: Keyboard
    target_events:
      - gamepad:
          button: Guide
      - gamepad:
          button: North
  - name: QuickAccess2
    source_event:
      gamepad:
        button: QuickAccess2
    target_events:
      - gamepad:
          button: Guide
      - gamepad:
          button: East
