//! # D-Bus interface proxy for: `org.freedesktop.PolicyKit1.Authority`
//!
//! This code was generated by `zbus-xmlgen` `4.1.0` from D-Bus introspection data.
//! Source: `Interface '/org/freedesktop/PolicyKit1/Authority' from service 'org.freedesktop.PolicyKit1' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "org.freedesktop.PolicyKit1.Authority",
    default_service = "org.freedesktop.PolicyKit1",
    default_path = "/org/freedesktop/PolicyKit1/Authority"
)]
trait Authority {
    /// AuthenticationAgentResponse method
    fn authentication_agent_response(
        &self,
        cookie: &str,
        identity: &(
            &str,
            std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
        ),
    ) -> zbus::Result<()>;

    /// AuthenticationAgentResponse2 method
    fn authentication_agent_response2(
        &self,
        uid: u32,
        cookie: &str,
        identity: &(
            &str,
            std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
        ),
    ) -> zbus::Result<()>;

    /// CancelCheckAuthorization method
    fn cancel_check_authorization(&self, cancellation_id: &str) -> zbus::Result<()>;

    /// CheckAuthorization method
    fn check_authorization(
        &self,
        subject: &(
            &str,
            std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
        ),
        action_id: &str,
        details: std::collections::HashMap<&str, &str>,
        flags: u32,
        cancellation_id: &str,
    ) -> zbus::Result<(bool, bool, std::collections::HashMap<String, String>)>;

    /// EnumerateActions method
    #[allow(clippy::type_complexity)]
    fn enumerate_actions(
        &self,
        locale: &str,
    ) -> zbus::Result<
        Vec<(
            String,
            String,
            String,
            String,
            String,
            String,
            u32,
            u32,
            u32,
            std::collections::HashMap<String, String>,
        )>,
    >;

    /// EnumerateTemporaryAuthorizations method
    #[allow(clippy::type_complexity)]
    fn enumerate_temporary_authorizations(
        &self,
        subject: &(
            &str,
            std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
        ),
    ) -> zbus::Result<
        Vec<(
            String,
            String,
            (
                String,
                std::collections::HashMap<String, zbus::zvariant::OwnedValue>,
            ),
            u64,
            u64,
        )>,
    >;

    /// RegisterAuthenticationAgent method
    fn register_authentication_agent(
        &self,
        subject: &(
            &str,
            std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
        ),
        locale: &str,
        object_path: &str,
    ) -> zbus::Result<()>;

    /// RegisterAuthenticationAgentWithOptions method
    fn register_authentication_agent_with_options(
        &self,
        subject: &(
            &str,
            std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
        ),
        locale: &str,
        object_path: &str,
        options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// RevokeTemporaryAuthorizationById method
    fn revoke_temporary_authorization_by_id(&self, id: &str) -> zbus::Result<()>;

    /// RevokeTemporaryAuthorizations method
    fn revoke_temporary_authorizations(
        &self,
        subject: &(
            &str,
            std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
        ),
    ) -> zbus::Result<()>;

    /// UnregisterAuthenticationAgent method
    fn unregister_authentication_agent(
        &self,
        subject: &(
            &str,
            std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
        ),
        object_path: &str,
    ) -> zbus::Result<()>;

    /// Changed signal
    #[zbus(signal)]
    fn changed(&self) -> zbus::Result<()>;

    /// BackendFeatures property
    #[zbus(property)]
    fn backend_features(&self) -> zbus::Result<u32>;

    /// BackendName property
    #[zbus(property)]
    fn backend_name(&self) -> zbus::Result<String>;

    /// BackendVersion property
    #[zbus(property)]
    fn backend_version(&self) -> zbus::Result<String>;
}
